# Generated by Django 5.1.5 on 2025-02-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_delete_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='title',
        ),
    ]
